sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
branches:
  only:
  - master
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - ./install_packer.sh || travis_terminate 1
  - pip install pre-commit
  - export AWS_PROFILE="default"
  - export AWS_REGION="us-east-1"
stages:
  - name: validate
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: deploy
      script:
        - travis_wait 30 ./build.sh || travis_terminate 1
