- hosts: all
  become: yes

  tasks:
    - name: install system updates for centos systems
      yum: name=* state=latest update_cache=yes
      when: ansible_distribution == "CentOS"

    - name: install system updates for ubuntu systems
      apt: upgrade=dist update_cache=yes
      when: ansible_distribution == "Ubuntu"

    - name: install packages
      package:
        name:
          - "ntpdate"
          - "curl"
        state: present

    # awscli and amazon-ssm-agent are on aws linux2 by default
    - name: Install awscli and amazon-ssm-agent if available in Snappy
      snappable_distros: Ubuntu # a comma-separated list of distributions with snapd
      snap:
        name:
          - aws-cli
          - amazon-ssm-agent
        classic: yes
      when: ansible_distribution in '{{ snappable_distros }}'

    - name: Install amazon-ssm-agent if Centos
      shell: "yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm && systemctl enable amazon-ssm-agent"
      when: ansible_distribution == "CentOS"

    - name: Check if JumpCloud is already installed
      shell: "[ -d /opt/jc ] && echo 'Found' || echo ''"
      register: jc_installed

    - name: Update time
      shell: "ntpdate -u pool.ntp.org"
      when: "not jc_installed.stdout"

    - name: Install JumpCloud
      shell: "curl --header 'x-connect-key: {{ lookup('env','JcConnectKey') }}' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
      args:
        warn: False
      when: "not jc_installed.stdout"
