- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  tasks:
    # No need to upgrade distribution, only need to install
    # causes an Could not get lock /var/lib/dpkg/lock-frontend error
    # - name: install system updates for ubuntu systems
    #   apt: upgrade=dist
    #   when: ansible_distribution == "Ubuntu"

    - name: install packages
      environment:
        MY_ENV_VARIABLE: DEBIAN_FRONTEND=noninteractive
      package:
        name:
          - "ntpdate"
          - "curl"
          - "dpkg-dev"
          - "zlib1g-dev"
          - "libssl-dev"
          - "libffi-dev"
          - "libcurl4-openssl-dev"
        state: present

    - name: Prep snap classic
      shell: "[ -x /snap ] || yum install -y epel-release snapd && systemctl enable --now snapd.socket && ln -s /var/lib/snapd/snap /snap || echo ''"
      register: snap_installed

    # awscli and amazon-ssm-agent are on aws linux2 by default
    - name: Install awscli and amazon-ssm-agent
      snap:
        name:
          - aws-cli
          - amazon-ssm-agent
        classic: yes
      when: "not snap_installed.stdout"

    - name: Check if JumpCloud is already installed
      shell: "[ -d /opt/jc ] && echo 'Found' || echo ''"
      register: jc_installed

    - name: Update time
      shell: "ntpdate -u pool.ntp.org"
      when: "not jc_installed.stdout"

    - name: Install JumpCloud
      shell: "curl --header 'x-connect-key: {{ lookup('env','JcConnectKey') }}' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
      args:
        warn: False
      when: "not jc_installed.stdout"

    - name: Install synapser
      shell: "R -e \"install.packages('synapser', repos=c('http://ran.synapse.org', 'http://cran.fhcrc.org'))\""

    - name: Install reticulate
      shell: "R -e \"iinstall.packages('reticulate')\""

    - name: Install synapseclient
      shell: "pip3 install synapseclient"
